# Generated by Django 5.1.6 on 2025-02-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='cor_casa',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='partida',
            name='cor_fora',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
