# Generated by Django 5.1.6 on 2025-02-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas_app', '0002_partida_cor_casa_partida_cor_fora'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='odds_empate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
