# Generated by Django 5.1.6 on 2025-02-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas_app', '0003_partida_odds_empate'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='modalidade',
            field=models.CharField(choices=[('fem', 'feminino'), ('masc', 'masculino')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
