# Generated by Django 5.1.6 on 2025-02-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas_app', '0004_partida_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='ambasMarcamNao',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='partida',
            name='ambasMarcamSim',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='partida',
            name='maisGols',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='partida',
            name='menosGols',
            field=models.FloatField(default=False),
        ),
    ]
