# Generated by Django 5.1.6 on 2025-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('fem', 'feminino'), ('masc', 'masculino')], max_length=4)),
                ('time_casa', models.CharField(max_length=100)),
                ('time_fora', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('odds_casa', models.FloatField()),
                ('odds_fora', models.FloatField()),
                ('odds_empate', models.FloatField()),
                ('ambasMarcamSim', models.FloatField(default=0.0)),
                ('ambasMarcamNao', models.FloatField(default=0.0)),
                ('maisGols', models.FloatField(default=0.0)),
                ('menosGols', models.FloatField(default=0.0)),
                ('cor_casa', models.CharField(default='#000000', max_length=7)),
                ('cor_fora', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
