# Generated by Django 5.1.6 on 2025-03-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='idPartida',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
