# Generated by Django 5.1.6 on 2025-03-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0004_partida_idpartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='ambasMarcamNao',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='ambasMarcamSim',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='maisGols',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='menosGols',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='odds_casa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='odds_empate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='odds_fora',
            field=models.IntegerField(),
        ),
    ]
